name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate short sha
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.IMAGE }}:${{ steps.sha_short.outputs.sha_short }}

      - name: Configure kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Update Kubernetes deployment
        run: make update-deployment DEPLOYMENT_NAME=${{ vars.DEPLOYMENT_NAME }} CONTAINER_NAME=${{ vars.CONTAINER_NAME }} IMAGE=${{ vars.IMAGE }} TAG=${{  steps.sha_short.outputs.sha_short }}

